# Generated by Django 5.1 on 2024-08-20 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                ("blog_content", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("blog_id", models.UUIDField(verbose_name=uuid.uuid5)),
                ("url", models.URLField()),
            ],
        ),
    ]
