# Generated by Django 5.1 on 2024-08-20 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="id",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="blog_id",
            field=models.UUIDField(
                default=uuid.uuid5,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
