# Generated by Django 5.1 on 2024-08-20 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blogpost_id_alter_blogpost_blog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blog_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
