# Generated by Django 5.1 on 2024-08-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_blog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionPost",
            fields=[
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogpost",
                    ),
                ),
                ("versions", models.JSONField()),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
