# Generated by Django 5.1 on 2024-08-24 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_versionpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parentId", models.CharField(blank=True, max_length=50, null=True)),
                ("replyId", models.UUIDField(default=uuid.uuid4)),
                ("upvote", models.IntegerField(blank=True, null=True)),
                ("downvote", models.IntegerField(blank=True, null=True)),
                ("childrenReplyId", models.JSONField(default=[])),
                ("replyData", models.TextField()),
                ("hasReply", models.BooleanField(default=False)),
                ("replyDate", models.DateTimeField(auto_now_add=True)),
                ("updateReplyDate", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
