# Generated by Django 5.1 on 2024-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_replypost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replypost",
            name="childrenReplyId",
            field=models.JSONField(default={}),
        ),
    ]
