# Generated by Django 5.1 on 2024-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_replypost_childrenreplyid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replypost",
            name="childrenReplyId",
            field=models.JSONField(default=dict),
        ),
    ]
